baseURL = "http://example.org/"
languageCode = "en-us"
title = "MojoAuth"
publishDir = "public/blog"

# Enable for syntax highlighting
pygmentsClass = true
pygmentsCodefences = true
pygmentsStyle = "friendly"

[taxonomies]
  author = "author"
  tag = "tags"