baseURL = "https://mojoauth.com/blog"
languageCode = "en-us"
title = "MojoAuth"
publishDir = "public/blog"

# Enable for syntax highlighting
pygmentsClass = true
pygmentsCodefences = true
pygmentsStyle = "friendly"

[taxonomies]
  author = "author"
  tag = "tags"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

enableRobotsTXT = true