baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "mojoauth" 

# Enable for syntax highlighting
pygmentsClass = true
pygmentsCodefences = true
pygmentsStyle = "friendly"